# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200716_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
