# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200716_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='static/portfolio'),
        ),
    ]
